spring:
    datasource:
        url: jdbc:postgresql://localhost:6543/aequitas_central
        username: aequitas
        password: aequitas
    jpa:
        show-sql: false
        properties:
            hibernate:
                show-sql: false
outbox:
    relay-interval: PT2S
logging:
    level:
        "[org.hibernate.sql]": WARN
